### PR TITLE
Evolution search - Fix CORS issue (#13)

### LINKED ISSUE #13: getEvolutionChain returning CORS error
##### This issue is about getEvolutionChain returning a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) error.
---
When using the `evolution-search` branch of the project, we're receiving this error, which seems to be a CORS issue:

@joshuahunt10 Can you paste the stack trace you're getting?

- [x] I ensure that this issue is not a duplicate of any current open issues(s).
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #13 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have tested the changes locally and they are functional.
- [x] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [x] This pull request has a descriptive title. For example, `Added/Fixed {Feature/Bug}`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -1,18 +1,53 @@
...
+  constructor(props) {
+    super(props);
+    this.state = {
+      searchInput: ""
+    };
+  }
+  handleEvolve = e => {
+    e.preventDefault();
+    console.log("evolve button clicked");
+    let evo = this.state.searchInput;
```
Comment (collinsnji) [inline src/App.js]: Can this be re-written to 
```javascript 
    let evo = this.state.searchInput.toLowerCase();
```
All the keys in pokedex are in lowercase. It will throw an error when for example the input is "Pikachu" instead of "pikachu"

**Review by collinsnji — APPROVED** [review]
It looks great by the way :)

File: src/App.js (hunk 1 above)
Comment (deadbirdi) [reply src/App.js]: Yes!

**Review by anshumanv — APPROVED** [review]
:+1:
